const referencesData = [
 {
   "id": 1,
   "author": "Greta Thunberg",
   "title": "You did not act in time': Greta Thunberg's full speech to MPs",
   "publisher": "The Guardian",
   "date": "23rd April",
   "year": 2019,
   "link": "https://www.theguardian.com/environment/2019/apr/23/greta-thunberg-full-speech-to-mps-you-did-not-act-in-time",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 2,
   "author": "NI Design Chat, Slack Group",
   "title": "Companies with designers in Northern Ireland",
   "publisher": "Google Sheets",
   "date": "",
   "year": 2020,
   "link": "https://docs.google.com/spreadsheets/d/1YxvuU0IYXEFWEmddc9N1be7lYxuzPdgRDd3fjsPmewk/edit?fbclid=IwAR2wh4omWlTw_hQkzoyi3SVyAH8HGg38WhcbxTE4eOHnAl8JQ3Vr66bS7Hk#gid=0",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 3,
   "author": "David Wallace-Wells",
   "title": "The Uninhabitable Earth",
   "publisher": "Penguin",
   "date": "",
   "year": 2019,
   "link": "",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 4,
   "author": "",
   "title": "The impacts of climate change at 1.5C, 2C and beyond",
   "publisher": "",
   "date": "4th October",
   "year": 2018,
   "link": "https://interactive.carbonbrief.org/impacts-climate-change-one-point-five-degrees-two-degrees/",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 5,
   "author": "Kurzgesagt",
   "title": "Is it too late to stop climate change? Well, it's complicated.",
   "publisher": "Youtube",
   "date": "29th September",
   "year": 2020,
   "link": "https://www.youtube.com/watch?v=wbR-5mHI6bo&list=PLFs4vir_WsTyXrrpFstD64Qj95vpy-yo1&ab_channel=Kurzgesagt%E2%80%93InaNutshell",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 6,
   "author": "Asim Hussain",
   "title": "Take the Green pill and I'll show you how deep the rabbit hole goes",
   "publisher": "asim.dev",
   "date": "16th February",
   "year": 2020,
   "link": "https://asim.dev/articles/climate-change-101/",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 7,
   "author": "Greta Thunberg",
   "title": "You did not act in time': Greta Thunberg's full speech to MPs",
   "publisher": "The Guardian",
   "date": "23rd April",
   "year": 2019,
   "link": "https://www.theguardian.com/environment/2019/apr/23/greta-thunberg-full-speech-to-mps-you-did-not-act-in-time",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 8,
   "author": "PBS NewsHour",
   "title": "WATCH: Greta Thunberg's full speech to world leaders at UN Climate Action Summit",
   "publisher": "Youtube",
   "date": "23rd September",
   "year": 2019,
   "link": "https://www.youtube.com/watch?v=KAJsdgTPJpU&ab_channel=PBSNewsHour",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 9,
   "author": "United Nations",
   "title": "The Paris Agreement",
   "publisher": "United Nations",
   "date": "",
   "year": 2020,
   "link": "https://unfccc.int/process-and-meetings/the-paris-agreement/the-paris-agreement",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 10,
   "author": "Andrew Beattie",
   "title": "The 3 Pillars of Corporate Sustainability",
   "publisher": "Investopedia",
   "date": "16th June",
   "year": 2019,
   "link": "https://www.investopedia.com/articles/investing/100515/three-pillars-corporate-sustainability.asp",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 11,
   "author": "Google",
   "title": "Carbon neutral since 2007. Carbon free by 2030.",
   "publisher": "Google",
   "date": "",
   "year": "",
   "link": "https://sustainability.google/commitments/#leading-at-google",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 12,
   "author": "Gerry McGovern",
   "title": "World Wide Waste",
   "publisher": "Silver Beach Publishing",
   "date": "",
   "year": 2020,
   "link": "https://gerrymcgovern.com/books/world-wide-waste/",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 13,
   "author": "Gerry McGovern",
   "title": "World Wide Waste",
   "publisher": "Silver Beach Publishing",
   "date": "",
   "year": 2020,
   "link": "https://gerrymcgovern.com/books/world-wide-waste/",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 14,
   "author": "Oxford Dictionary",
   "title": "Cloud Computing",
   "publisher": "Google",
   "date": "",
   "year": "",
   "link": "https://www.google.com/search?q=define+cloud+computing&oq=define+cloud+&aqs=chrome.0.0i457j0l2j69i57j0l4.11473j1j9&sourceid=chrome&ie=UTF-8",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 15,
   "author": "Oxford Dictionary",
   "title": "Data Centre",
   "publisher": "Google",
   "date": "",
   "year": "",
   "link": "https://www.google.com/search?sxsrf=ALeKk03kY84ShsmPpizmWYHZFlM82nJ9aQ%3A1607518852995&ei=hMrQX4KkPMbKgQaPg7CgBQ&q=data+center+definition",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 16,
   "author": "Yevgeniy Sverdlik",
   "title": "Analysts: There are Now More than 500 Hyperscale Data Centers in the World",
   "publisher": "Data Center Knowledge",
   "date": "17th October",
   "year": 2019,
   "link": "https://www.datacenterknowledge.com/cloud/analysts-there-are-now-more-500-hyperscale-data-centers-world",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 17,
   "author": "Przemek Chojecki",
   "title": "How Big is Big Data?",
   "publisher": "Towards Data Science",
   "date": "31st January",
   "year": 2019,
   "link": "https://towardsdatascience.com/how-big-is-big-data-3fb14d5351ba",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 18,
   "author": "Jenna Baker",
   "title": "H5 Data Centers Announces Expansion of its Atlanta Edge Data Center",
   "publisher": "H5 Data Centers",
   "date": "4th May",
   "year": 2018,
   "link": "https://h5datacenters.com/h5-atlanta.html#:~:text=H5%20Data%20Centers%20is%20one,data%20center%20space%20under%20management.",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 19,
   "author": "",
   "title": "Power Grid",
   "publisher": "Collins",
   "date": "",
   "year": 2020,
   "link": "https://www.collinsdictionary.com/dictionary/english/power-grid",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 20,
   "author": "Sean Donnelly",
   "title": "Electricity Consumption and Renewable Generation Statistics",
   "publisher": "Department for the Economy",
   "date": "",
   "year": 2020,
   "link": "https://www.economy-ni.gov.uk/articles/electricity-consumption-and-renewable-generation-statistics",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 21,
   "author": "Department for the Business, Energy & Industrial Strategy",
   "title": "2018 UK GREENHOUSE\nGAS EMISSIONS,\nPROVISIONAL FIGURE",
   "publisher": "Department for the Business, Energy & Industrial Strategy",
   "date": "28th March",
   "year": 2019,
   "link": "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/790626/2018-provisional-emissions-statistics-report.pdf",
   "place": "UK",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 22,
   "author": "IEA",
   "title": "Data Centres and Data Transmission Networks",
   "publisher": "IEA",
   "date": "June",
   "year": 2020,
   "link": "https://www.iea.org/reports/data-centres-and-data-transmission-networks",
   "place": "Paris",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 23,
   "author": "Mary Meehan",
   "title": "What Your Data Isn't Telling You: Dark Data Presents Problems And Opportunities For Big Businesses",
   "publisher": "Forbes",
   "date": "4th June",
   "year": 2019,
   "link": "https://www.forbes.com/sites/marymeehan/2019/06/04/what-your-data-isnt-telling-you-dark-data-presents-problems-and-opportunities-for-big-businesses/?sh=2d389829484e",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 24,
   "author": "Apple",
   "title": "Activity Monitor User Guide",
   "publisher": "Apple",
   "date": "",
   "year": 2020,
   "link": "https://support.apple.com/en-gb/guide/activity-monitor/welcome/mac",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 25,
   "author": "obdev",
   "title": "Little Snitch: Makes the invisible visible!",
   "publisher": "obdev",
   "date": "",
   "year": 2020,
   "link": "https://www.obdev.at/products/littlesnitch/index.html",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 26,
   "author": "CRAZY_AnieL",
   "title": "Can you use OneNote without OneDrive?",
   "publisher": "reddit",
   "date": "",
   "year": 2015,
   "link": "https://www.reddit.com/r/OneNote/comments/2x9jkq/can_you_use_onenote_without_onedrive/",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 27,
   "author": "Theron Mathis",
   "title": "JPEG or PNG? – Increasing Page Speed with Proper Image Formatting",
   "publisher": "Interactive Search Marketing",
   "date": "5th June",
   "year": 2014,
   "link": "https://www.interactivesearchmarketing.com/jpeg-png-proper-image-formatting/#:~:text=The%20full%2Dsize%20PNG%20has,quality%20is%20far%20more%20noticeable.",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 28,
   "author": "w3 Techs",
   "title": "Usage statistics and market share of WordPress",
   "publisher": "w3 Techs",
   "date": "",
   "year": 2020,
   "link": "https://w3techs.com/technologies/details/cm-wordpress",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 29,
   "author": "lauren orsini",
   "title": "How Etsy Reinvented Its Development Process",
   "publisher": "readwrite",
   "date": "5th Feb",
   "year": 2015,
   "link": "https://readwrite.com/2015/02/05/etsy-reinvented-development-process/#:~:text=The%20Etsy%20codebase%20is%20primarily,used%20for%20front%20end%20design.",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 30,
   "author": "Senthilkumar R",
   "title": "Data Usage",
   "publisher": "Chrome Web Store",
   "date": "28th September",
   "year": 2020,
   "link": "https://chrome.google.com/webstore/detail/data-usage/dopfdeikfpadofngjnjokfgmboicnppc/related?hl=en-GB",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 31,
   "author": "SimilarWeb",
   "title": "Etsy Traffic Overview",
   "publisher": "SimilarWeb",
   "date": "November",
   "year": 2020,
   "link": "https://www.similarweb.com/website/etsy.com/",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 32,
   "author": "Hardik Shah",
   "title": "12 Popular Websites that use React in Production",
   "publisher": "Simform",
   "date": "9th January",
   "year": 2020,
   "link": "https://www.simform.com/websites-use-react/#Reddit",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 33,
   "author": "SIMS Recycling Solutions",
   "title": "Data Centers: The Life Cycle of a Server",
   "publisher": "SIMS Recycling Solutions",
   "date": "",
   "year": "",
   "link": "https://i.pinimg.com/564x/cb/69/f6/cb69f68097d934c1f9c7e714e1ee156b.jpg",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 34,
   "author": "UK Green Building Council",
   "title": "Embodied Carbon: Developing a client brief",
   "publisher": "Derwent London plc",
   "date": "June",
   "year": 2016,
   "link": "https://www.ukgbc.org/sites/default/files/UK-GBC%20EC%20Developing%20Client%20Brief.pdf",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 35,
   "author": "Dell",
   "title": "PowerEdge R640",
   "publisher": "Dell",
   "date": "January",
   "year": 2019,
   "link": "https://i.dell.com/sites/csdocuments/CorpComm_Docs/en/carbon-footprint-poweredge-r640.pdf",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 36,
   "author": "Asim Hussain",
   "title": "Embodied Carbon",
   "publisher": "Principles.Green",
   "date": "",
   "year": 2020,
   "link": "https://principles.green/principles/embodied-carbon/",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 37,
   "author": "Larry Dignan",
   "title": "AWS cloud computing ops, data centers, 1.3 million servers creating efficiency flywheel",
   "publisher": "ZDNet",
   "date": "7th June",
   "year": 2016,
   "link": "https://www.zdnet.com/article/aws-cloud-computing-ops-data-centers-1-3-million-servers-creating-efficiency-flywheel/",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 38,
   "author": "Jorge Alberto Falcón Hernández",
   "title": "How many servers does AWS have?",
   "publisher": "Quora",
   "date": "14th February",
   "year": 2020,
   "link": "https://www.quora.com/How-many-servers-does-AWS-have",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 39,
   "author": "Paul Johnston & Anne Currie",
   "title": "The State of Data Center Energy Use in 2018",
   "publisher": "The Coed:Ethics Community\n",
   "date": "28th September",
   "year": 2018,
   "link": "https://docs.google.com/document/d/1eCCb3rgqtQxcRwLdTr0P_hCK_drIZrm1Dpb4dlPeG6M/edit",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 40,
   "author": "Carla Tardi",
   "title": "What Is Moore's Law?",
   "publisher": "Investopedia",
   "date": "27th August",
   "year": 2020,
   "link": "https://www.investopedia.com/terms/m/mooreslaw.asp",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 41,
   "author": "Will Kenton",
   "title": "What Is Planned Obsolescence?",
   "publisher": "Investopedia",
   "date": "4th June",
   "year": 2019,
   "link": "https://www.investopedia.com/terms/p/planned_obsolescence.asp",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 42,
   "author": "United Nations",
   "title": "UN report: Time to seize opportunity, tackle challenge of e-waste",
   "publisher": "United Nations Environmental Programme",
   "date": "24th January",
   "year": 2019,
   "link": "https://www.unenvironment.org/news-and-stories/press-release/un-report-time-seize-opportunity-tackle-challenge-e-waste",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 43,
   "author": "Ben Schoon",
   "title": "Google made an actual product graveyard for Halloween w/ G+, Reader, more",
   "publisher": "9to5google",
   "date": "4th October",
   "year": 2019,
   "link": "https://9to5google.com/2019/10/04/google-product-graveyard-halloween/",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 44,
   "author": "",
   "title": "The Google Cemetery",
   "publisher": "gcemetery",
   "date": "",
   "year": "",
   "link": "https://gcemetery.co/page/12/",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 45,
   "author": "Tim Anderson",
   "title": "Supporting Internet Explorer is hell': Web developers identify top needs – new survey",
   "publisher": "The Register",
   "date": "20th December",
   "year": 2019,
   "link": "https://www.theregister.com/2019/12/20/web_devs_identify_top_needs_in_new_survey/",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 46,
   "author": "",
   "title": "Internet Explorer 11",
   "publisher": "Wikipedia",
   "date": "",
   "year": "",
   "link": "https://en.wikipedia.org/wiki/Internet_Explorer_11",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 47,
   "author": "Tom Warren",
   "title": "Microsoft will bid farewell to Internet Explorer and legacy Edge in 2021",
   "publisher": "The Verge",
   "date": "17th August",
   "year": 2020,
   "link": "https://www.theverge.com/2020/8/17/21372487/microsoft-internet-explorer-11-support-end-365-legacy-edge",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 48,
   "author": "",
   "title": "U.S. V. Microsoft: Proposed Findings of Fact",
   "publisher": "The United States Department of Justice",
   "date": "",
   "year": "",
   "link": "https://www.justice.gov/atr/us-v-microsoft-proposed-findings-fact-1",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 49,
   "author": "Vijay",
   "title": "What computer/laptop do big tech companies give to their engineers and programmers",
   "publisher": "Techworm",
   "date": "25th July",
   "year": 2020,
   "link": "https://www.techworm.net/2016/11/computerlaptop-big-tech-companies-give-engineers-programmers.html#:~:text=Microsoft%20unquestioning%20trusts%20Lenovo%20for,was%20used%20for%20engineering%2Fprogramming.",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 50,
   "author": "",
   "title": "ThinkPad W series",
   "publisher": "Wikipedia",
   "date": "",
   "year": "",
   "link": "https://en.wikipedia.org/wiki/ThinkPad_W_series#:~:text=One%20white%20ThinkLight-,W530,to%20the%20prior%20W%20models.",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 51,
   "author": "Avram Piltch",
   "title": "Lenovo ThinkPad W530 Review",
   "publisher": "Laptop Mag",
   "date": "20th July",
   "year": 2012,
   "link": "https://www.laptopmag.com/uk/reviews/laptops/lenovo-thinkpad-w530#:~:text=upped%20the%20settings.-,Battery%20Life,8%20hours%20and%202%20minutes).",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 52,
   "author": "Navck",
   "title": "Re: How long does it take you to charge your battery?",
   "publisher": "thinkpads.com",
   "date": "11th July",
   "year": 2010,
   "link": "https://forum.thinkpads.com/viewtopic.php?t=88819#:~:text=Your%20Thinkpad%20will%20take%20between,monitor%20their%20temperature%20during%20charge.",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 53,
   "author": "Avram Piltch",
   "title": "Lenovo ThinkPad W530 Review",
   "publisher": "Laptop Mag",
   "date": "20th July",
   "year": 2012,
   "link": "https://www.laptopmag.com/uk/reviews/laptops/lenovo-thinkpad-w530#:~:text=upped%20the%20settings.-,Battery%20Life,8%20hours%20and%202%20minutes).",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 54,
   "author": "Department for Business, Energy & Industrial Strategy",
   "title": "2018 UK Greenhouse\nGas Emissions, Provisional Figures",
   "publisher": "Department for Business, Energy & Industrial Strategy",
   "date": "28th March",
   "year": 2019,
   "link": "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/790626/2018-provisional-emissions-statistics-report.pdf",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 55,
   "author": "Asim Hussain, Manifesto",
   "title": "LCAW 2020: The environmental impact of the digital industry",
   "publisher": "Youtube",
   "date": "November",
   "year": 2020,
   "link": "https://www.youtube.com/watch?v=qauz5ErVB2M&feature=emb_imp_woyt&ab_channel=Manifesto",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 56,
   "author": "Evan Wallace",
   "title": "WebAssembly cut Figma's load time by 3x",
   "publisher": "Figma",
   "date": "8th June",
   "year": 2017,
   "link": "https://www.figma.com/blog/webassembly-cut-figmas-load-time-by-3x/",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 57,
   "author": "Tom Greenwood, Manifesto",
   "title": "LCAW 2020: The environmental impact of the digital industry",
   "publisher": "Youtube",
   "date": "November",
   "year": 2020,
   "link": "https://www.youtube.com/watch?v=qauz5ErVB2M&feature=emb_imp_woyt&ab_channel=Manifesto",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 58,
   "author": "Mark Hayes",
   "title": "Home Shopify Blog 10 Must Know Image Optimization Tips\n10 Must Know Image Optimization Tips",
   "publisher": "Shopify",
   "date": "30th March",
   "year": 2018,
   "link": "https://www.shopify.co.uk/blog/7412852-10-must-know-image-optimization-tips#four",
   "place": "",
   "page": "",
   "dissertation": ""
 },
 {
   "id": 59,
   "author": "Laurent Devernay",
   "title": "How to Audit your website on a budget",
   "publisher": "sustainable.dev",
   "date": "6th Semptember",
   "year": 2020,
   "link": "https://the-sustainable.dev/how-to-audit-your-website-on-a-budget/",
   "place": "",
   "page": "",
   "dissertation": ""
 }
];
